export const ERROR_CODES = {
  AUTH: {
    INVALID_TOKEN_FORMAT: "ERR_AUTH_INVALID_TOKEN_FORMAT",
    MISSING_BEARER_TOKEN: "ERR_AUTH_MISSING_BEARER_TOKEN",
    MISSING_REFRESH_TOKEN: "ERR_AUTH_MISSING_REFRESH_TOKEN",
    INVALID_REFRESH_TOKEN: "ERR_AUTH_INVALID_REFRESH_TOKEN",
    INVALID_EMAIL_VERIFY_TOKEN: "ERR_AUTH_INVALID_EMAIL_VERIFY_TOKEN",
    INVALID_FORGOT_PASSWORD_TOKEN: "ERR_AUTH_INVALID_FORGOT_PASSWORD_TOKEN",
    TOKEN_EXPIRED: "ERR_AUTH_TOKEN_EXPIRED",
    INVALID_TOKEN: "ERR_AUTH_INVALID_TOKEN",
  },

  VALIDATION: {
    FAILED: "ERR_VALIDATION_FAILED",
    INVALID_BODY: "ERR_VALIDATION_INVALID_BODY",
    INVALID_QUERY: "ERR_VALIDATION_INVALID_QUERY",
    INVALID_PARAMS: "ERR_VALIDATION_INVALID_PARAMS",
    INVALID_PAYLOAD: "ERR_VALIDATION_INVALID_PAYLOAD",
    INVALID_COOKIES: "ERR_VALIDATION_INVALID_COOKIES",
    UNSUPPORTED_MEDIA_TYPE: "ERR_VALIDATION_UNSUPPORTED_MEDIA_TYPE",
  },

  UPLOAD: {
    INVALID_FILE_TYPE: "ERR_UPLOAD_INVALID_FILE_TYPE",
    EXTENSION_MISMATCH: "ERR_UPLOAD_EXTENSION_MISMATCH",
    FILE_SIZE_EXCEEDED: "ERR_UPLOAD_FILE_SIZE_EXCEEDED",
    MAX_FILES_EXCEEDED: "ERR_UPLOAD_MAX_FILES_EXCEEDED",
    MAX_FILES_SIZE_EXCEEDED: "ERR_UPLOAD_MAX_FILES_SIZE_EXCEEDED",
    TOTAL_SIZE_EXCEEDED: "ERR_UPLOAD_TOTAL_SIZE_EXCEEDED",
    MISSING_IMAGE_KEY: "ERR_UPLOAD_MISSING_IMAGE_KEY",
    MISSING_VIDEO_KEY: "ERR_UPLOAD_MISSING_VIDEO_KEY",
  },

  TWEETS: {
    NOT_FOUND: "ERR_TWEET_NOT_FOUND",
    PARENT_NOT_FOUND: "ERR_TWEET_PARENT_NOT_FOUND",
    FORBIDDEN_ACTION: "ERR_TWEET_FORBIDDEN_ACTION",
  },

  USERS: {
    NOT_FOUND: "ERR_USER_NOT_FOUND",
    USERNAME_ALREADY_EXISTS: "ERR_USER_USERNAME_ALREADY_EXISTS",
    ACCOUNT_IS_BANNED: "ERR_USER_ACCOUNT_IS_BANNED",
    CANNOT_ACTION_SELF: "ERR_USER_CANNOT_ACTION_SELF",
    ALREADY_FOLLOWED: "ERR_USER_ALREADY_FOLLOWED",
    NOT_FOLLOWED_YET: "ERR_USER_NOT_FOLLOWED_YET",
    OLD_PASSWORD_NOT_MATCH: "ERR_USER_OLD_PASSWORD_NOT_MATCH",
  },

  FORMIDABLE: {
    MAX_FILE_SIZE: 1016,
    MAX_FILES: 1015,
    MAX_TOTAL_FILE_SIZE: 1009,
  },

  MONGOOSE: {
    VALIDATION: "ERR_MONGOOSE_VALIDATION",
  },

  DB: {
    DUPLICATE_KEY: "ERR_DB_DUPLICATE_KEY",
    MONGO_DUPLICATE_KEY: 11000,
  },

  SYSTEM: {
    INVALID_JSON_SYNTAX: "ERR_SYSTEM_INVALID_JSON_SYNTAX",
    INTERNAL_SERVER_ERROR: "ERR_INTERNAL_SERVER_ERROR",
  },

  THIRD_PARTY: {
    GOOGLE_AUTH_FAILED: "ERR_THIRD_PARTY_GOOGLE_AUTH_FAILED",
    GOOGLE_USER_INFO_FAILED: "ERR_THIRD_PARTY_GOOGLE_USER_INFO_FAILED",
    NETWORK_ERROR: "ERR_THIRD_PARTY_NETWORK_ERROR",
  },

  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  EMAIL_IS_VERIFIED: "EMAIL_IS_VERIFIED",
  ACCOUNT_IS_BANNED: "ACCOUNT_IS_BANNED",
  PASSWORD_INCORRECT: "PASSWORD_INCORRECT",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  RESEND_EMAIL_TOO_FAST: "RESEND_EMAIL_TOO_FAST",
  VALIDATION_ERROR: "ValidationError",
  GMAIL_NOT_VERIFIED: "ERR_GMAIL_NOT_VERIFIED",
  TOO_MANY_REQUESTS: "ERR_TOO_MANY_REQUESTS",
} as const;
